/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["webLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["webRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["webLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mobile/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mobileLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mobile/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mobileRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mobile/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mobileLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExercises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoutines"];
        put?: never;
        post: operations["createRoutine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkouts"];
        put?: never;
        post: operations["createWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["progressOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exerciseProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycle/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCycleEntries"];
        put?: never;
        post: operations["upsertCycleEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycle/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCycleEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["readinessCheckin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            fieldErrors?: {
                [key: string]: string[];
            };
            retryable: boolean;
            /** Format: uuid */
            requestId: string;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshInput: {
            refreshToken: string;
        };
        MobileTokens: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            name: string;
            trackCycle: boolean;
            /** @enum {string} */
            biologicalSex?: "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_SAY";
        };
        Exercise: {
            id: string;
            name: string;
            imagePath?: string | null;
            gifPath?: string | null;
            muscleGroup?: string;
            equipment?: string;
        };
        Routine: {
            id: string;
            name: string;
            exercises: {
                [key: string]: unknown;
            }[];
        };
        RoutineInput: {
            name: string;
            notes?: string;
            exercises: {
                [key: string]: unknown;
            }[];
        };
        WorkoutSet: {
            id: string;
            /** Format: uuid */
            clientId?: string | null;
            exerciseId: string;
            order: number;
            revision: number;
            weightKg?: number | null;
            reps?: number | null;
            durationS?: number | null;
            rpe?: number | null;
        };
        Workout: {
            id: string;
            /** Format: uuid */
            clientId?: string | null;
            name: string;
            /** @enum {string} */
            status: "ACTIVE" | "COMPLETED" | "CANCELLED";
            revision: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
            sets: components["schemas"]["WorkoutSet"][];
        };
        SyncWorkoutSetInput: {
            /** Format: uuid */
            clientId: string;
            baseRevision: number;
            exerciseId: string;
            order: number;
            weightKg?: number | null;
            reps?: number | null;
            durationS?: number | null;
            rpe?: number | null;
        };
        SyncWorkoutInput: {
            /** Format: uuid */
            clientId: string;
            /** Format: uuid */
            syncId: string;
            baseRevision: number;
            name: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string;
            /** Format: date-time */
            cancelledAt?: string;
            /** @enum {string} */
            status: "ACTIVE" | "COMPLETED" | "CANCELLED";
            notes?: string;
            routineId?: string;
            sets: components["schemas"]["SyncWorkoutSetInput"][];
            deletedSetClientIds: string[];
        };
        SyncWorkoutResult: {
            workout: components["schemas"]["Workout"];
            revision: number;
            mapping: {
                [key: string]: unknown;
            };
        };
        CycleEntry: {
            id: string;
            /** Format: date */
            date: string;
            /** @enum {string} */
            flow?: "NONE" | "SPOTTING" | "LIGHT" | "MEDIUM" | "HEAVY";
            symptoms?: string[];
        };
        CycleEntryInput: {
            /** Format: date */
            date: string;
            /** Format: date */
            previousDate?: string;
            /** @enum {string} */
            flow?: "NONE" | "SPOTTING" | "LIGHT" | "MEDIUM" | "HEAVY";
            symptoms?: string[];
            notes?: string;
        };
    };
    responses: {
        /** @description Short-lived access token */
        AccessToken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    accessToken: string;
                };
            };
        };
        /** @description Mobile access and rotating refresh token */
        MobileTokens: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MobileTokens"];
            };
        };
        /** @description Operation succeeded */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @constant */
                    ok: true;
                };
            };
        };
        /** @description Normalized API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        Period: "30d" | "90d" | "6m" | "1y" | "all";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    webLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            200: components["responses"]["AccessToken"];
            401: components["responses"]["Error"];
        };
    };
    webRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AccessToken"];
            401: components["responses"]["Error"];
        };
    };
    webLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    mobileLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            200: components["responses"]["MobileTokens"];
            401: components["responses"]["Error"];
        };
    };
    mobileRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshInput"];
            };
        };
        responses: {
            200: components["responses"]["MobileTokens"];
            401: components["responses"]["Error"];
        };
    };
    mobileLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshInput"];
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listExercises: {
        parameters: {
            query?: {
                search?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated exercise catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Exercise"][];
                        nextCursor?: string | null;
                    };
                };
            };
        };
    };
    listRoutines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Routines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Routine"][];
                };
            };
        };
    };
    createRoutine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineInput"];
            };
        };
        responses: {
            /** @description Created routine */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Routine"];
                };
            };
        };
    };
    listWorkouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workouts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workout"][];
                };
            };
        };
    };
    createWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    notes?: string;
                    routineId?: string;
                    /** Format: uuid */
                    clientId?: string;
                };
            };
        };
        responses: {
            /** @description Active workout */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workout"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    syncWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncWorkoutInput"];
            };
        };
        responses: {
            /** @description Canonical synchronized workout */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncWorkoutResult"];
                };
            };
            /** @description Revision or active-workout conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"] & {
                        serverVersion?: components["schemas"]["Workout"];
                    };
                };
            };
        };
    };
    progressOverview: {
        parameters: {
            query?: {
                period?: components["parameters"]["Period"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated progress overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    exerciseProgress: {
        parameters: {
            query?: {
                period?: components["parameters"]["Period"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated exercise progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listCycleEntries: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cycle entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleEntry"][];
                };
            };
        };
    };
    upsertCycleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CycleEntryInput"];
            };
        };
        responses: {
            /** @description Cycle entry */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleEntry"];
                };
            };
        };
    };
    deleteCycleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    readinessCheckin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Daily readiness */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            503: components["responses"]["Error"];
        };
    };
}
